import "@/ui/globals.css";
import SideBar from "@/app/components/sideBar";
import NavBar from "@/app/components/navBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className="felx text-white bg-[#000000]">
            <div className="flex justify-center max-[1000px]:flex-col">
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.10.1/devicon.min.css"></link>

                <NavBar/>
                <section className="grid grid-cols-2 gap-0 max-[1300px]:grid-cols-1 max-[1300px]:grid-rows-2">
                    <SideBar/>

                    <main className="flex items-center max-[1000px]:justify-center">
                        {children}
                    </main>
                </section>
            </div>
        </body>
    </html>
  );
}
